### ISSUE TITLE
How are you using accounts?

### ISSUE THREAD

**Issue by okken** [EnhancedJax/Bagels#14]
I'm thinking of accounts as different bank accounts, so I'd expect the income and expense "insights" to be across all accounts.
However, if you're using the more as budget buckets, and not tied to financial institution accounts, your setup makes more sense.
Is that how you are using it?

**Comment by EnhancedJax** [comment]
Hmm... Accounts is simply like as you said financial institution accounts. Income and expense insights *is* across all accounts, and you can switch to account view, which shows records and insights only for the selected account, by pressing \ (indicated by the symbol on the bottom left hand corner). 

Or are you questioning about the "selection" of accounts? For the modules above the insights, they all act as a "default value" for the records you create, so you don't have to select them every time. For my use case, for example I have 4 entries for my transit card account basically every day, so I would find it more convenient to select that account on the left, and enter the records. I understand this might be less straight forward sometimes though, but overtime it makes more sense.


However, I've never really thought about them as budgets, and budgeting is a planned future to be implemented.

**Comment by okken** [comment]
I’ve just started playing with it and perhaps just misunderstood what was going on. I’ll play with it more. Thanks.
