### ISSUE TITLE
Is there a way to export to CSV or Parquet or something similar?

### ISSUE THREAD

**Issue by araichev** [EnhancedJax/Bagels#18]
I can't find this feature in the current Bagels, but i'm a newb.
Would be a useful feature so i can integrate with other tools that take such output as input.

**Comment by EnhancedJax** [comment]
all data is saved in a db file. You can locate it using the locate command, and export to csv using any db export tool!

**Comment by araichev** [comment]
Sweet. SQLite?

**Comment by EnhancedJax** [comment]
Yep!
