### ISSUE TITLE
Arguable bug: original categories won't die

### ISSUE THREAD

**Issue by araichev** [EnhancedJax/Bagels#20]
I deleted all the default Bagels categories and created my own, but when i create a new record, the old categories are still there as options (along with the new ones), which is confusing.

![categories](https://github.com/user-attachments/assets/2e8b5f45-5b74-4152-a020-fba5fa624182)
![record_categories](https://github.com/user-attachments/assets/db1dc340-d455-4c21-9a65-83709af3cb07)

**Comment by EnhancedJax** [comment]
Thanks for the report, I'll fix this asap!

**Comment by EnhancedJax** [comment]
Fixed in 0.1.15
