### ISSUE TITLE
ValidationError: Crash when adding subcategories after opening categories

### ISSUE THREAD

**Issue by Zimzozaur** [EnhancedJax/Bagels#3]
**Describe the Bug**
When pressing `c` to open categories and `s` to add subcategories, the app throws the following error:
`ValidationError: 1 validation error for FormField` after fresh installation.

**Steps to Reproduce:**
1. Open the app bagels.
2. Press `c` to open categories.
3. Press `s` to add subcategories.

**Comment by EnhancedJax** [comment]
Fix in 0.1.8! Thanks for the report!

**Comment by Zimzozaur** [comment]
You're welcome!
