### ISSUE TITLE
Beancount backend?

### ISSUE THREAD

**Issue by matthiasbeyer** [EnhancedJax/Bagels#5]
Hi!

I found this wonderful project via [this toot](https://social.linux.pizza/@willmcgugan@mastodon.social/113514781104101558) and wanted to show you [beancount](https://github.com/beancount/beancount) - maybe you're not aware of it?

It would be absolutely lovely if your app would use beancount as backend. I know you already made an effort implementing the actual logic, but maybe providing a beancount backend and integrating into the beancount ecosystem could benefit both this project and the beancount project? :wink: 

Either way, thanks for your effort here, this looks awesome! :heart:

**Comment by EnhancedJax** [comment]
Hi! Thanks for the issue. I've actually done a bit of research before starting on this project, and I understand that beancount has its own merits, but for the sake of having a system more suitable for my own use cases and customizability, I thought it'd be better if I created my own system.
