### ISSUE TITLE
[Question] How do we set 1st day of week?

### ISSUE THREAD

**Issue by Geobert** [EnhancedJax/Bagels#7]
Hi,

I read in the Readme that we can configure things with `config.yaml` but I can’t find any documentation/example file to do it.

Am I missing it somehow?

Regards,

**Comment by EnhancedJax** [comment]
You can locate the config file with `bagels local config` and edit the file directly!

**Comment by Geobert** [comment]
But what are le values?

there’s no file at C:\Users\Geob\.config\bagels\config.yaml

I need to create it but I don’t know the available keys :)

**Comment by EnhancedJax** [comment]
It should create all keys in the latest version. Try upgrading using `uv tool upgrade bagels` and see if they appear!

**Comment by Geobert** [comment]
Indeed! Thanks!
