### ISSUE TITLE
Crashes after pressing `g` on the date picker

### ISSUE THREAD

**Issue by tconbeer** [EnhancedJax/Bagels#9]
Nice work on bagels! I especially like the date picker widget. I quickly made it crash, though.

**To reproduce:**
`uvx --python 3.13 bagels`
press Tab to focus on the date picker
press `g`

**Result:**
Bagels crashes and produces this trace:
<details>
<pre>
╭─────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────────────────────────────────────────╮
│ /home/tco/.cache/uv/archive-v0/Gw7AS632utNOaxf026oRS/lib/python3.13/site-packages/textual/widget.py:4213 in _compose                                                                     │
│                                                                                                                                                                                          │
│   4210 │                                                                                        ╭───────────────────────────── locals ──────────────────────────────╮                    │
│   4211 │   async def _compose(self) -> None:                                                    │ error = AttributeError("'list' object has no attribute 'fields'") │                    │
│   4212 │   │   try:                                                                             │  self = Fields()                                                  │                    │
│ ❱ 4213 │   │   │   widgets = [*self._pending_children, *compose(self)]                          ╰───────────────────────────────────────────────────────────────────╯                    │
│   4214 │   │   │   self._pending_children.clear()                                                                                                                                        │
│   4215 │   │   except TypeError as error:                                                                                                                                                │
│   4216 │   │   │   raise TypeError(                                                                                                                                                      │
│                                                                                                                                                                                          │
│ /home/tco/.cache/uv/archive-v0/Gw7AS632utNOaxf026oRS/lib/python3.13/site-packages/bagels/components/fields.py:23 in compose                                                              │
│                                                                                                                                                                                          │
│    20 │   │   self.form = fields                                                               ╭──── locals ─────╮                                                                       │
│    21 │                                                                                        │ self = Fields() │                                                                       │
│    22 │   def compose(self) -> ComposeResult:                                                  ╰─────────────────╯                                                                       │
│ ❱  23 │   │   for field in self.form.fields:                                                                                                                                             │
│    24 │   │   │   yield Field(field)                                                                                                                                                     │
│    25                                                                                                                                                                                    │
│    26                                                                                                                                                                                    │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'list' object has no attribute 'fields'
</pre>
</details>

**Comment by EnhancedJax** [comment]
Fixed in 0.1.11! Thanks for the report!
